when@dev:
    web_profiler:
        toolbar: true
        intercept_redirects: false
 
    framework:
        profiler:
            collect_serializer_data: false
 
when@test:
    framework:
        profiler: { collect: false }